#ifndef _FTPCLIENT_CONFIG_H_
#define _FTPCLIENT_CONFIG_H_

#define ASIO_HAS_BOOST_DATE_TIME
#define GLOG_NO_ABBREVIATED_SEVERITIES
#define GOOGLE_GLOG_DLL_DECL 


#endif // _FTPCLIENT_CONFIG_H_